# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

# All the ones without a comment were the ones that are currently violated
# by the codebase. The plan is to fix them all (when sensible) and then enable them.
exclude = ["**/*.ipynb"]
fix = true
line-length = 120
show-fixes = true
target-version = "py311"


[format]
line-ending = "lf"

[lint]
select = ["ALL"]
ignore = [
    "CPY001", # Missing copyright notice at top of file
    "D401",   # First line of docstring should be in imperative mood
    "PTH123", # `open()` should be replaced by `Path.open()`
    "DTZ005", # `datetime.datetime.now()` called without a `tz` argument
    "DTZ006", # `datetime.datetime.fromtimestamp()` called without a `tz` argument
    "FBT001", # Boolean positional arg in function definition
    "FBT002", # Boolean default value in function definition
    "S101",   # Use of assert detected,
]


[lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false

[lint.isort]
known-first-party = ["GrossOrders"]

[lint.mccabe]
max-complexity = 25

[lint.per-file-ignores]
"nardole/integrations/gmail/models.py" = ["N815"]
"nardole/integrations/gcontacts/models.py" = ["N815"]

[lint.pydocstyle]
convention = "pep257"

[lint.pylint]
max-args = 10
max-branches = 25
max-returns = 15
max-statements = 50

[lint.pyupgrade]
keep-runtime-typing = true
